/**
 * California DMV Driver's License Practice Questions
 * Sources: California Driver Handbook (official) + real DMV test patterns
 * 89 questions across 6 topics — English base, translations added separately
 */

export const californiaDMV = {
  category: {
    name: "California Driver's License",
    nameEn: "California Driver's License",
    description: "California DMV Knowledge Test — 46 questions, 83% to pass (38/46 correct)",
    icon: "🚗",
    color: "#EF4444",
    hasAiTutor: false,
    translations: [
      {
        language: "zh",
        name: "加州驾照笔试",
        description: "加州 DMV 驾照知识考试 — 共 46 题，答对 38 题（83%）即通过",
      },
      {
        language: "es",
        name: "Licencia de Conducir de California",
        description: "Examen de conocimientos del DMV de California — 46 preguntas, 83% para aprobar",
      },
    ],
  },
  topics: [
    // ─── TOPIC 1: Traffic Signs & Signals ──────────────────────────────────────
    {
      name: "Traffic Signs & Signals",
      nameEn: "Traffic Signs & Signals",
      description: "Road signs, traffic signals, pavement markings",
      handbookUrl: "https://www.dmv.ca.gov/portal/handbook/california-driver-handbook/introduction-to-driving/",
      translations: [
        { language: "zh", name: "交通标志与信号灯", description: "道路标志、信号灯、路面标线" },
        { language: "es", name: "Señales de Tráfico y Semáforos", description: "Señales viales, semáforos y marcas en el pavimento" },
      ],
      questions: [
        {
          content: "A five-sided (pentagon) shaped sign indicates:",
          explanation: "Pentagon-shaped signs are used exclusively for school zones and school crossings. Their unique shape helps drivers recognize school areas even at a distance or in poor visibility.",
          handbookSection: "Traffic Controls — Sign Shapes",
          difficulty: 1,
          options: [
            { content: "A school zone or school crossing", isCorrect: true },
            { content: "A construction work zone", isCorrect: false },
            { content: "A no-passing zone", isCorrect: false },
            { content: "A railroad crossing", isCorrect: false },
          ],
        },
        {
          content: "What does a blue curb indicate?",
          explanation: "Blue curbs mark parking spaces reserved for people with disabilities. Only vehicles displaying a valid disabled person placard or license plate may park at a blue curb.",
          handbookSection: "Traffic Controls — Curb Colors",
          difficulty: 1,
          options: [
            { content: "No parking at any time", isCorrect: false },
            { content: "Parking for persons with disabilities only", isCorrect: true },
            { content: "Limited-time parking", isCorrect: false },
            { content: "Commercial vehicle loading zone", isCorrect: false },
          ],
        },
        {
          content: "Double solid white lines on the road mean:",
          explanation: "Double solid white lines indicate that changing lanes is not permitted. These lines separate lanes of traffic moving in the same direction where lane changes would be dangerous.",
          handbookSection: "Traffic Controls — Pavement Markings",
          difficulty: 2,
          options: [
            { content: "You may cross them to pass slow vehicles", isCorrect: false },
            { content: "Changing lanes is not allowed", isCorrect: true },
            { content: "A reversible lane is ahead", isCorrect: false },
            { content: "A construction work zone is ahead", isCorrect: false },
          ],
        },
        {
          content: "A flashing yellow traffic light means:",
          explanation: "A flashing yellow light is a warning signal. You should slow down and proceed with caution, but you are not required to stop.",
          handbookSection: "Traffic Controls — Traffic Signals",
          difficulty: 1,
          options: [
            { content: "Stop and wait for a green light", isCorrect: false },
            { content: "The light is about to turn red", isCorrect: false },
            { content: "Slow down and proceed with caution", isCorrect: true },
            { content: "Come to a complete stop", isCorrect: false },
          ],
        },
        {
          content: "What must you do when you see a solid red arrow at a traffic light?",
          explanation: "A solid red arrow means you must stop completely and do not turn in the direction the arrow is pointing. Unlike a circular red light, you may NOT turn on red when there is a red arrow, unless a sign specifically permits it.",
          handbookSection: "Traffic Controls — Traffic Signals",
          difficulty: 2,
          options: [
            { content: "You may turn after yielding to oncoming traffic", isCorrect: false },
            { content: "Stop completely and do not turn in that direction", isCorrect: true },
            { content: "Turn only if no pedestrians are in the crosswalk", isCorrect: false },
            { content: "Treat it like a stop sign and proceed when safe", isCorrect: false },
          ],
        },
        {
          content: "A green arrow pointing left while the regular traffic light is also green means:",
          explanation: "A green arrow indicates a protected turn — oncoming traffic is stopped by a red light, so you may turn safely in the direction of the arrow. You still must yield to pedestrians in the crosswalk.",
          handbookSection: "Traffic Controls — Traffic Signals",
          difficulty: 2,
          options: [
            { content: "You must yield to oncoming traffic before turning", isCorrect: false },
            { content: "You have a protected turn; oncoming traffic is stopped", isCorrect: true },
            { content: "You may only turn left if no traffic is coming", isCorrect: false },
            { content: "Wait for the regular green light before turning", isCorrect: false },
          ],
        },
        {
          content: "You may turn right on a red light ONLY if:",
          explanation: "A right turn on red is permitted after a complete stop, when there is no 'No Turn on Red' sign posted, and when you yield to pedestrians and cross traffic. You must stop first — rolling through is illegal.",
          handbookSection: "Traffic Controls — Traffic Signals",
          difficulty: 1,
          options: [
            { content: "You slow down and no cars are coming", isCorrect: false },
            { content: "You stop, yield to pedestrians and traffic, and no sign prohibits it", isCorrect: true },
            { content: "There is no pedestrian in the crosswalk", isCorrect: false },
            { content: "It is safe to proceed without stopping", isCorrect: false },
          ],
        },
        {
          content: "An octagon (8-sided) shaped sign always means:",
          explanation: "The octagon shape is used exclusively for STOP signs. This unique shape allows drivers to recognize a stop sign even if the color or lettering is obscured.",
          handbookSection: "Traffic Controls — Sign Shapes",
          difficulty: 1,
          options: [
            { content: "Yield to oncoming traffic", isCorrect: false },
            { content: "Stop completely", isCorrect: true },
            { content: "Slow down, school zone ahead", isCorrect: false },
            { content: "Railroad crossing ahead", isCorrect: false },
          ],
        },
        {
          content: "A triangular (three-sided) shaped sign means:",
          explanation: "Triangular signs are yield signs. You must slow down and be prepared to stop to let vehicles with the right-of-way pass. Unlike a stop sign, you do not have to come to a complete stop unless necessary.",
          handbookSection: "Traffic Controls — Sign Shapes",
          difficulty: 1,
          options: [
            { content: "Stop completely before proceeding", isCorrect: false },
            { content: "Yield — slow down and give right-of-way to other traffic", isCorrect: true },
            { content: "School zone ahead, reduce speed", isCorrect: false },
            { content: "Warning: hazard ahead", isCorrect: false },
          ],
        },
        {
          content: "What does a red curb indicate?",
          explanation: "A red curb means no stopping, standing, or parking at any time. These are typically found near fire hydrants, bus stops, or intersections where stopping would create a hazard.",
          handbookSection: "Traffic Controls — Curb Colors",
          difficulty: 1,
          options: [
            { content: "No parking, but you may stop briefly to load/unload", isCorrect: false },
            { content: "No stopping, standing, or parking at any time", isCorrect: true },
            { content: "Parking allowed only during business hours", isCorrect: false },
            { content: "Emergency vehicles only", isCorrect: false },
          ],
        },
        {
          content: "A yellow curb means:",
          explanation: "A yellow curb indicates a loading and unloading zone for commercial vehicles. The driver must stay with the vehicle.",
          handbookSection: "Traffic Controls — Curb Colors",
          difficulty: 2,
          options: [
            { content: "Parking for disabled persons only", isCorrect: false },
            { content: "No parking at any time", isCorrect: false },
            { content: "Commercial loading/unloading — driver must remain in vehicle", isCorrect: true },
            { content: "Passenger pickup and drop-off only", isCorrect: false },
          ],
        },
        {
          content: "A white curb means:",
          explanation: "A white curb is for passenger loading and unloading only. You may stop briefly to pick up or drop off passengers but must remain in or near the vehicle.",
          handbookSection: "Traffic Controls — Curb Colors",
          difficulty: 2,
          options: [
            { content: "Parking for any vehicle for up to 5 minutes", isCorrect: false },
            { content: "Passenger loading and unloading only", isCorrect: true },
            { content: "No parking during school hours", isCorrect: false },
            { content: "Bus stop only", isCorrect: false },
          ],
        },
        {
          content: "What does a pennant-shaped sign indicate?",
          explanation: "The pennant sign is placed on the left side of the road and warns drivers they are entering a no-passing zone. It is always yellow with black text.",
          handbookSection: "Traffic Controls — Sign Shapes",
          difficulty: 2,
          options: [
            { content: "Keep right — passing allowed on left only", isCorrect: false },
            { content: "No passing zone begins here", isCorrect: true },
            { content: "Yield to oncoming traffic", isCorrect: false },
            { content: "School crossing zone ahead", isCorrect: false },
          ],
        },
        {
          content: "When approaching a railroad crossing, you must stop at least:",
          explanation: "California law requires you to stop at least 15 feet from the nearest rail when a train is approaching or crossing gates are down.",
          handbookSection: "Traffic Controls — Railroad Crossings",
          difficulty: 2,
          options: [
            { content: "5 feet from the tracks", isCorrect: false },
            { content: "10 feet from the tracks", isCorrect: false },
            { content: "15 feet from the nearest rail", isCorrect: true },
            { content: "25 feet from the crossing gate", isCorrect: false },
          ],
        },
        {
          content: "Orange-colored signs on the highway typically indicate:",
          explanation: "Orange signs are used in construction and maintenance work zones. Fines are doubled in these zones.",
          handbookSection: "Traffic Controls — Sign Colors",
          difficulty: 1,
          options: [
            { content: "School zones with children present", isCorrect: false },
            { content: "Construction or maintenance work zones", isCorrect: true },
            { content: "Hazardous material transport routes", isCorrect: false },
            { content: "Detour or alternate route ahead", isCorrect: false },
          ],
        },
        {
          content: "A steady yellow traffic light means:",
          explanation: "A steady yellow light warns that the signal is about to turn red. Stop if you can do so safely. If too close to stop safely, you may cautiously continue through.",
          handbookSection: "Traffic Controls — Traffic Signals",
          difficulty: 1,
          options: [
            { content: "Speed up to get through before it turns red", isCorrect: false },
            { content: "Stop if you can do so safely", isCorrect: true },
            { content: "You have the right-of-way to proceed at full speed", isCorrect: false },
            { content: "Slow down to 15 mph and proceed", isCorrect: false },
          ],
        },
        {
          content: "Broken white lines between lanes of traffic mean:",
          explanation: "Broken white lines separate lanes of traffic moving in the same direction. You may cross broken white lines to change lanes when it is safe.",
          handbookSection: "Traffic Controls — Pavement Markings",
          difficulty: 1,
          options: [
            { content: "Two-way traffic — passing is prohibited", isCorrect: false },
            { content: "Lanes moving the same direction — lane changes permitted when safe", isCorrect: true },
            { content: "Lanes moving in opposite directions", isCorrect: false },
            { content: "No lane changing allowed", isCorrect: false },
          ],
        },
        {
          content: "A solid yellow line on your side of the center line means:",
          explanation: "A solid yellow line on your side means no passing is permitted from your side. Passing is only allowed from the side with a broken yellow line.",
          handbookSection: "Traffic Controls — Pavement Markings",
          difficulty: 2,
          options: [
            { content: "You may pass when oncoming traffic is clear", isCorrect: false },
            { content: "Passing is not permitted from your side", isCorrect: true },
            { content: "Passing is allowed with caution", isCorrect: false },
            { content: "This is a two-way left-turn lane", isCorrect: false },
          ],
        },
        {
          content: "When a school bus displays flashing red lights, you must:",
          explanation: "All traffic from both directions must stop when a school bus has flashing red lights (except on divided highways with a physical barrier). Remain stopped until the lights stop and the bus moves.",
          handbookSection: "Traffic Controls — School Buses",
          difficulty: 1,
          options: [
            { content: "Slow to 15 mph and pass with caution", isCorrect: false },
            { content: "Stop from both directions — children may be crossing", isCorrect: true },
            { content: "Only oncoming traffic must stop", isCorrect: false },
            { content: "Stop only if a child is visible near the road", isCorrect: false },
          ],
        },
        {
          content: "What does it mean when both a green light AND a green left-turn arrow are displayed?",
          explanation: "When both are displayed, left-turning vehicles have a protected turn (oncoming traffic is stopped). After the arrow turns off, you may still turn left on the green light but must yield to oncoming traffic.",
          handbookSection: "Traffic Controls — Traffic Signals",
          difficulty: 2,
          options: [
            { content: "You must wait for oncoming traffic to clear before turning", isCorrect: false },
            { content: "Left-turning vehicles have a protected turn with no conflicting traffic", isCorrect: true },
            { content: "You may turn left only from the far left lane", isCorrect: false },
            { content: "Pedestrians have the right-of-way over turning vehicles", isCorrect: false },
          ],
        },
      ],
    },

    // ─── TOPIC 2: Right-of-Way Rules ───────────────────────────────────────────
    {
      name: "Right-of-Way Rules",
      nameEn: "Right-of-Way Rules",
      description: "Who goes first at intersections, crosswalks, and special situations",
      handbookUrl: "https://www.dmv.ca.gov/portal/handbook/california-driver-handbook/laws-and-rules-of-the-road/",
      translations: [
        { language: "zh", name: "行驶优先权", description: "路口、人行横道及特殊情况下谁先行" },
        { language: "es", name: "Reglas de Preferencia de Paso", description: "Quién tiene prioridad en intersecciones, cruces peatonales y situaciones especiales" },
      ],
      questions: [
        {
          content: "At a four-way stop, two cars arrive at exactly the same time. Who has the right-of-way?",
          explanation: "When two vehicles arrive at a four-way stop simultaneously, the vehicle on the RIGHT has the right-of-way. This is the standard rule whenever arrival times are equal.",
          handbookSection: "Laws and Rules — Right-of-Way at Intersections",
          difficulty: 1,
          options: [
            { content: "The vehicle on the left", isCorrect: false },
            { content: "The vehicle on the right", isCorrect: true },
            { content: "The vehicle traveling on the larger road", isCorrect: false },
            { content: "The vehicle going straight", isCorrect: false },
          ],
        },
        {
          content: "At an uncontrolled intersection, who has the right-of-way?",
          explanation: "The vehicle that arrives first has the right-of-way. If two vehicles arrive at the same time, yield to the vehicle on your right.",
          handbookSection: "Laws and Rules — Right-of-Way at Intersections",
          difficulty: 2,
          options: [
            { content: "Vehicles traveling on the wider road", isCorrect: false },
            { content: "The vehicle that arrived first; if simultaneous, the vehicle on the right", isCorrect: true },
            { content: "Vehicles going straight always have priority", isCorrect: false },
            { content: "The larger vehicle always has priority", isCorrect: false },
          ],
        },
        {
          content: "When turning left at an intersection on a green light (no arrow), you must yield to:",
          explanation: "On a green light without a green arrow, you must yield to oncoming vehicles and pedestrians. The green light gives permission to enter the intersection, not to turn unsafely.",
          handbookSection: "Laws and Rules — Turning",
          difficulty: 1,
          options: [
            { content: "No one — a green light gives you the right-of-way", isCorrect: false },
            { content: "Oncoming vehicles and pedestrians", isCorrect: true },
            { content: "Only pedestrians in the crosswalk", isCorrect: false },
            { content: "Only emergency vehicles", isCorrect: false },
          ],
        },
        {
          content: "A pedestrian using a white cane or guide dog is at a crosswalk. You must:",
          explanation: "Blind pedestrians using a white cane or guide dog have the right-of-way at all times and in all locations. You must wait until they have completely crossed the road.",
          handbookSection: "Laws and Rules — Pedestrians",
          difficulty: 2,
          options: [
            { content: "Slow down and proceed if they are not in your lane", isCorrect: false },
            { content: "Stop and wait until they have completely crossed", isCorrect: true },
            { content: "Honk to alert them that you are proceeding", isCorrect: false },
            { content: "Proceed if the traffic signal says go", isCorrect: false },
          ],
        },
        {
          content: "At a T-intersection, which vehicles have the right-of-way?",
          explanation: "Vehicles on the through road (the top of the T) have the right-of-way over vehicles on the terminating road (the stem of the T).",
          handbookSection: "Laws and Rules — Right-of-Way at Intersections",
          difficulty: 2,
          options: [
            { content: "The vehicle that arrives first", isCorrect: false },
            { content: "Vehicles on the through (continuing) road", isCorrect: true },
            { content: "The larger vehicle", isCorrect: false },
            { content: "The vehicle turning right", isCorrect: false },
          ],
        },
        {
          content: "On a mountain road with only room for one car, who has the right-of-way?",
          explanation: "The vehicle heading uphill has the right-of-way. The vehicle going downhill must pull over or back up. It is more difficult and dangerous to control a vehicle while backing uphill.",
          handbookSection: "Laws and Rules — Right-of-Way on Mountain Roads",
          difficulty: 2,
          options: [
            { content: "The vehicle going downhill", isCorrect: false },
            { content: "The vehicle going uphill", isCorrect: true },
            { content: "The larger vehicle", isCorrect: false },
            { content: "The vehicle that honks first", isCorrect: false },
          ],
        },
        {
          content: "When an emergency vehicle with flashing lights approaches, you must:",
          explanation: "You must immediately pull to the right side of the road and stop. Remain stopped until the vehicle passes. Never drive in the same path as the emergency vehicle.",
          handbookSection: "Laws and Rules — Emergency Vehicles",
          difficulty: 1,
          options: [
            { content: "Speed up to get out of its way", isCorrect: false },
            { content: "Pull to the right and stop until it passes", isCorrect: true },
            { content: "Slow down and move to the center of the road", isCorrect: false },
            { content: "Pull to the left shoulder and stop", isCorrect: false },
          ],
        },
        {
          content: "You must NEVER do what when another vehicle has stopped at a crosswalk?",
          explanation: "You may never drive past a vehicle stopped at a crosswalk for a pedestrian. The stopped vehicle may be blocking your view of someone crossing. You must also stop.",
          handbookSection: "Laws and Rules — Pedestrians",
          difficulty: 2,
          options: [
            { content: "Stop behind it", isCorrect: false },
            { content: "Drive past it", isCorrect: true },
            { content: "Flash your lights at pedestrians", isCorrect: false },
            { content: "Honk to warn pedestrians", isCorrect: false },
          ],
        },
        {
          content: "Who has the right-of-way when you are merging onto a freeway?",
          explanation: "Vehicles already on the freeway have the right-of-way. You must yield when merging and match the speed of freeway traffic.",
          handbookSection: "Laws and Rules — Freeway Driving",
          difficulty: 1,
          options: [
            { content: "You do, because you are entering the freeway", isCorrect: false },
            { content: "Vehicles already on the freeway", isCorrect: true },
            { content: "Whoever is going faster", isCorrect: false },
            { content: "You share it equally with freeway traffic", isCorrect: false },
          ],
        },
        {
          content: "Before turning right from a two-lane road, you should be in:",
          explanation: "Before turning right, move into the lane closest to the right curb. Signal about 100 feet before the turn. Turning from another lane is illegal.",
          handbookSection: "Laws and Rules — Turning",
          difficulty: 1,
          options: [
            { content: "Either lane — right turns can be made from any lane", isCorrect: false },
            { content: "The lane closest to the right curb", isCorrect: true },
            { content: "The left lane, to avoid hitting the curb", isCorrect: false },
            { content: "The center turn lane", isCorrect: false },
          ],
        },
        {
          content: "When backing out of a driveway, you must yield to:",
          explanation: "When backing out of a driveway, yield to all pedestrians on the sidewalk and to all vehicles on the street. You are entering the flow of traffic.",
          handbookSection: "Laws and Rules — Right-of-Way",
          difficulty: 1,
          options: [
            { content: "Only vehicles coming from the left", isCorrect: false },
            { content: "Pedestrians on the sidewalk and all vehicles on the street", isCorrect: true },
            { content: "Nothing — drivers in the road must yield to exiting vehicles", isCorrect: false },
            { content: "Only emergency vehicles", isCorrect: false },
          ],
        },
        {
          content: "A bicyclist is in front of you. California law requires you to give at least how much clearance when passing?",
          explanation: "California's Three Feet for Safety Act requires drivers to give cyclists at least 3 feet of clearance when passing. Do not honk immediately behind the cyclist as it can cause them to swerve.",
          handbookSection: "Laws and Rules — Sharing the Road",
          difficulty: 2,
          options: [
            { content: "1 foot", isCorrect: false },
            { content: "2 feet", isCorrect: false },
            { content: "3 feet", isCorrect: true },
            { content: "5 feet", isCorrect: false },
          ],
        },
        {
          content: "You want to enter a green-light intersection to turn left, but it is blocked with traffic. You should:",
          explanation: "Never enter an intersection if you cannot completely cross it before the light turns red ('blocking the box'). Wait before the intersection until there is room to complete your turn.",
          handbookSection: "Laws and Rules — Intersections",
          difficulty: 2,
          options: [
            { content: "Enter the intersection and wait in the center", isCorrect: false },
            { content: "Wait before the intersection until there is room to complete your turn", isCorrect: true },
            { content: "Turn on your hazard lights and enter the intersection", isCorrect: false },
            { content: "Honk at traffic to clear the way", isCorrect: false },
          ],
        },
        {
          content: "When must you yield to a pedestrian in California?",
          explanation: "In California, drivers must always yield to pedestrians in crosswalks, marked or unmarked, at intersections. Pedestrians always have the right-of-way in a crosswalk.",
          handbookSection: "Laws and Rules — Pedestrians",
          difficulty: 1,
          options: [
            { content: "Only when they are in a marked crosswalk", isCorrect: false },
            { content: "Always, in both marked and unmarked crosswalks at intersections", isCorrect: true },
            { content: "Only when the pedestrian signal shows 'Walk'", isCorrect: false },
            { content: "Only when the traffic light is red", isCorrect: false },
          ],
        },
        {
          content: "You are waiting to turn left at an intersection. The light turns yellow. Should you turn?",
          explanation: "Only turn if oncoming vehicles are actually stopping and it is genuinely safe. A yellow light to oncoming traffic means they should stop, but confirm they are stopping before proceeding.",
          handbookSection: "Laws and Rules — Turning",
          difficulty: 3,
          options: [
            { content: "Yes, turn quickly because the light is changing", isCorrect: false },
            { content: "Only if oncoming vehicles are stopping and it is safe", isCorrect: true },
            { content: "No, always wait for a green arrow to turn left", isCorrect: false },
            { content: "No, always wait until the intersection clears completely", isCorrect: false },
          ],
        },
      ],
    },

    // ─── TOPIC 3: Speed Limits ─────────────────────────────────────────────────
    {
      name: "Speed Limits",
      nameEn: "Speed Limits",
      description: "California speed laws, school zones, work zones, basic speed law",
      handbookUrl: "https://www.dmv.ca.gov/portal/handbook/california-driver-handbook/safe-driving/",
      translations: [
        { language: "zh", name: "速度限制", description: "加州限速规定、学区、施工区及基本速度法则" },
        { language: "es", name: "Límites de Velocidad", description: "Leyes de velocidad de California, zonas escolares, obras y ley básica de velocidad" },
      ],
      questions: [
        {
          content: "What is the maximum speed on a two-lane undivided highway in California, unless otherwise posted?",
          explanation: "The maximum speed on a two-lane undivided highway is 55 mph, unless signs indicate a higher limit.",
          handbookSection: "Safe Driving — Speed Limits",
          difficulty: 1,
          options: [
            { content: "45 mph", isCorrect: false },
            { content: "55 mph", isCorrect: true },
            { content: "65 mph", isCorrect: false },
            { content: "70 mph", isCorrect: false },
          ],
        },
        {
          content: "The maximum speed limit on most California freeways is:",
          explanation: "The maximum speed on most California freeways is 65 mph. Some freeways allow 70 mph when posted.",
          handbookSection: "Safe Driving — Speed Limits",
          difficulty: 1,
          options: [
            { content: "55 mph", isCorrect: false },
            { content: "60 mph", isCorrect: false },
            { content: "65 mph", isCorrect: true },
            { content: "75 mph", isCorrect: false },
          ],
        },
        {
          content: "What is the maximum speed in a school zone when children are present?",
          explanation: "The speed limit in a school zone when children are present is 25 mph. Fines for violations are doubled.",
          handbookSection: "Safe Driving — School Zones",
          difficulty: 1,
          options: [
            { content: "15 mph", isCorrect: false },
            { content: "20 mph", isCorrect: false },
            { content: "25 mph", isCorrect: true },
            { content: "35 mph", isCorrect: false },
          ],
        },
        {
          content: "The maximum speed in a residential district, unless otherwise posted, is:",
          explanation: "The maximum speed in a residential or business district is 25 mph. This limit protects pedestrians, cyclists, and children near the road.",
          handbookSection: "Safe Driving — Speed Limits",
          difficulty: 1,
          options: [
            { content: "15 mph", isCorrect: false },
            { content: "20 mph", isCorrect: false },
            { content: "25 mph", isCorrect: true },
            { content: "30 mph", isCorrect: false },
          ],
        },
        {
          content: "What is California's 'Basic Speed Law'?",
          explanation: "California's Basic Speed Law states you must never drive faster than is safe for current conditions, regardless of the posted speed limit.",
          handbookSection: "Safe Driving — Basic Speed Law",
          difficulty: 2,
          options: [
            { content: "You may drive up to 10 mph over the limit if traffic requires it", isCorrect: false },
            { content: "Never drive faster than is safe for current road and weather conditions", isCorrect: true },
            { content: "The posted speed limit is the minimum safe speed", isCorrect: false },
            { content: "Speed limits only apply during daylight hours", isCorrect: false },
          ],
        },
        {
          content: "When visibility is less than 100 feet due to heavy rain or fog, you must not drive faster than:",
          explanation: "When visibility drops below 100 feet due to weather, California law limits your speed to 30 mph.",
          handbookSection: "Safe Driving — Driving in Bad Weather",
          difficulty: 2,
          options: [
            { content: "15 mph", isCorrect: false },
            { content: "25 mph", isCorrect: false },
            { content: "30 mph", isCorrect: true },
            { content: "45 mph", isCorrect: false },
          ],
        },
        {
          content: "On wet or rainy roads, you should reduce your speed by approximately:",
          explanation: "On wet or rainy roads, reduce speed by 5 to 10 mph. Wet roads reduce traction and significantly increase stopping distance.",
          handbookSection: "Safe Driving — Driving in Bad Weather",
          difficulty: 2,
          options: [
            { content: "2 to 3 mph", isCorrect: false },
            { content: "5 to 10 mph", isCorrect: true },
            { content: "15 to 20 mph", isCorrect: false },
            { content: "Half the posted speed limit", isCorrect: false },
          ],
        },
        {
          content: "When driving on packed snow, you should reduce your speed to:",
          explanation: "On packed snow, reduce speed to half the normal limit. Snow significantly reduces traction and braking ability.",
          handbookSection: "Safe Driving — Driving in Bad Weather",
          difficulty: 2,
          options: [
            { content: "10 mph below the posted limit", isCorrect: false },
            { content: "Half the posted speed limit", isCorrect: true },
            { content: "A maximum of 25 mph", isCorrect: false },
            { content: "No more than 30 mph", isCorrect: false },
          ],
        },
        {
          content: "When driving on icy roads, you should drive no faster than:",
          explanation: "On icy roads, drive no faster than 5 mph. Ice provides almost no traction, and even at very low speeds sudden movements can cause the vehicle to slide.",
          handbookSection: "Safe Driving — Driving in Bad Weather",
          difficulty: 2,
          options: [
            { content: "15 mph", isCorrect: false },
            { content: "10 mph", isCorrect: false },
            { content: "5 mph", isCorrect: true },
            { content: "Half the speed limit", isCorrect: false },
          ],
        },
        {
          content: "The maximum speed in an alley is:",
          explanation: "The maximum speed in an alley in California is 15 mph. Alleys are narrow with limited visibility.",
          handbookSection: "Safe Driving — Speed Limits",
          difficulty: 2,
          options: [
            { content: "10 mph", isCorrect: false },
            { content: "15 mph", isCorrect: true },
            { content: "25 mph", isCorrect: false },
            { content: "No specific limit", isCorrect: false },
          ],
        },
        {
          content: "The maximum speed within 100 feet of a railroad crossing when you cannot see clearly is:",
          explanation: "When you cannot see at least 400 feet in both directions at a railroad crossing, California law limits your speed to 15 mph within 100 feet of the crossing.",
          handbookSection: "Safe Driving — Railroad Crossings",
          difficulty: 3,
          options: [
            { content: "10 mph", isCorrect: false },
            { content: "15 mph", isCorrect: true },
            { content: "25 mph", isCorrect: false },
            { content: "35 mph", isCorrect: false },
          ],
        },
        {
          content: "If you miss your exit on a freeway, you should:",
          explanation: "Continue to the next exit. Never back up on a freeway — it is extremely dangerous and illegal.",
          handbookSection: "Safe Driving — Freeway Driving",
          difficulty: 1,
          options: [
            { content: "Stop on the shoulder and back up to the exit", isCorrect: false },
            { content: "Continue to the next exit", isCorrect: true },
            { content: "Make a U-turn at the nearest gap in the median", isCorrect: false },
            { content: "Cross the median to return to the exit", isCorrect: false },
          ],
        },
        {
          content: "The minimum following distance on a freeway at 65 mph is:",
          explanation: "California recommends the 3-second rule. At 65 mph, 3 seconds equals about 286 feet. Increase to 4-5 seconds in poor conditions.",
          handbookSection: "Safe Driving — Following Distance",
          difficulty: 2,
          options: [
            { content: "1 second", isCorrect: false },
            { content: "2 seconds", isCorrect: false },
            { content: "3 seconds", isCorrect: true },
            { content: "5 seconds", isCorrect: false },
          ],
        },
        {
          content: "You are driving 55 mph and another vehicle passes you. You should:",
          explanation: "Maintain your speed and stay in your lane. Do not speed up to prevent them from passing — that is dangerous and illegal.",
          handbookSection: "Safe Driving — Passing",
          difficulty: 1,
          options: [
            { content: "Speed up so they cannot pass you", isCorrect: false },
            { content: "Maintain your speed and let them pass safely", isCorrect: true },
            { content: "Move to the left lane to block them", isCorrect: false },
            { content: "Flash your brake lights to warn them", isCorrect: false },
          ],
        },
        {
          content: "When you see brake lights ahead on a freeway, you should:",
          explanation: "Take your foot off the accelerator immediately and slow gradually. Briefly tapping your brakes turns on your brake lights to warn drivers behind you. Avoid sudden braking.",
          handbookSection: "Safe Driving — Freeway Driving",
          difficulty: 1,
          options: [
            { content: "Maintain speed until close, then brake hard", isCorrect: false },
            { content: "Ease off the accelerator and slow gradually, warn drivers behind", isCorrect: true },
            { content: "Immediately change lanes to avoid the slowdown", isCorrect: false },
            { content: "Turn on hazard lights and stop", isCorrect: false },
          ],
        },
      ],
    },

    // ─── TOPIC 4: DUI & Alcohol Laws ───────────────────────────────────────────
    {
      name: "DUI & Alcohol Laws",
      nameEn: "DUI & Alcohol Laws",
      description: "BAC limits, DUI penalties, open container laws",
      handbookUrl: "https://www.dmv.ca.gov/portal/handbook/california-driver-handbook/alcohol-and-drugs/",
      translations: [
        { language: "zh", name: "酒驾与药物法规", description: "血液酒精浓度限制、酒驾处罚、车内开放容器法规" },
        { language: "es", name: "Leyes de DUI y Alcohol", description: "Límites de BAC, penalidades por DUI, leyes de envase abierto" },
      ],
      questions: [
        {
          content: "What is the legal BAC limit for drivers 21 and older in California?",
          explanation: "It is illegal for drivers 21 and older to drive with a BAC of 0.08% or higher.",
          handbookSection: "Alcohol and Drugs — BAC Limits",
          difficulty: 1,
          options: [
            { content: "0.04%", isCorrect: false },
            { content: "0.06%", isCorrect: false },
            { content: "0.08%", isCorrect: true },
            { content: "0.10%", isCorrect: false },
          ],
        },
        {
          content: "What is the legal BAC limit for drivers UNDER 21 in California?",
          explanation: "California's Zero Tolerance law: any driver under 21 with a BAC of 0.01% or higher is in violation.",
          handbookSection: "Alcohol and Drugs — Zero Tolerance",
          difficulty: 1,
          options: [
            { content: "0.08%", isCorrect: false },
            { content: "0.05%", isCorrect: false },
            { content: "0.02%", isCorrect: false },
            { content: "0.01%", isCorrect: true },
          ],
        },
        {
          content: "What is the legal BAC limit for commercial driver's license (CDL) holders?",
          explanation: "CDL holders face a stricter limit of 0.04% — half the limit for regular drivers.",
          handbookSection: "Alcohol and Drugs — BAC Limits",
          difficulty: 2,
          options: [
            { content: "0.08%", isCorrect: false },
            { content: "0.06%", isCorrect: false },
            { content: "0.04%", isCorrect: true },
            { content: "0.02%", isCorrect: false },
          ],
        },
        {
          content: "A DUI conviction in California stays on your driving record for:",
          explanation: "A DUI conviction remains on your California record for 10 years and counts as a prior offense if you get another DUI.",
          handbookSection: "Alcohol and Drugs — DUI Consequences",
          difficulty: 2,
          options: [
            { content: "3 years", isCorrect: false },
            { content: "5 years", isCorrect: false },
            { content: "7 years", isCorrect: false },
            { content: "10 years", isCorrect: true },
          ],
        },
        {
          content: "If arrested for DUI and you refuse a chemical test, you will:",
          explanation: "Under California's implied consent law, refusing a chemical test results in automatic license suspension — typically 1 year for a first offense.",
          handbookSection: "Alcohol and Drugs — Implied Consent",
          difficulty: 2,
          options: [
            { content: "Be released without charge", isCorrect: false },
            { content: "Face automatic license suspension and other penalties", isCorrect: true },
            { content: "Only face a small fine", isCorrect: false },
            { content: "Have the DUI charges dismissed", isCorrect: false },
          ],
        },
        {
          content: "An open container of alcohol must be stored where in a vehicle?",
          explanation: "An open container must be kept in the trunk or behind the last upright seat — away from the driver and passengers.",
          handbookSection: "Alcohol and Drugs — Open Container Law",
          difficulty: 1,
          options: [
            { content: "Under the seat out of sight", isCorrect: false },
            { content: "In the glove compartment", isCorrect: false },
            { content: "In the trunk, away from the passenger area", isCorrect: true },
            { content: "In a bag in the back seat", isCorrect: false },
          ],
        },
        {
          content: "Which of the following can impair driving as much as alcohol?",
          explanation: "Prescription drugs, over-the-counter medications, marijuana, and illegal drugs can all impair driving. It is illegal to drive under the influence of ANY impairing drug.",
          handbookSection: "Alcohol and Drugs — Drug Impairment",
          difficulty: 2,
          options: [
            { content: "A cup of coffee", isCorrect: false },
            { content: "Prescription medications", isCorrect: true },
            { content: "Energy drinks", isCorrect: false },
            { content: "A large meal", isCorrect: false },
          ],
        },
        {
          content: "The ONLY thing that sobers you up after drinking is:",
          explanation: "Only time sobers you up. Your liver processes about one standard drink per hour. Coffee, cold showers, or exercise do NOT speed this up.",
          handbookSection: "Alcohol and Drugs — Sobering Up",
          difficulty: 1,
          options: [
            { content: "Drinking coffee or energy drinks", isCorrect: false },
            { content: "Taking a cold shower", isCorrect: false },
            { content: "Eating a large meal", isCorrect: false },
            { content: "Time — your body processes alcohol at a fixed rate", isCorrect: true },
          ],
        },
        {
          content: "It is illegal to drink alcohol or smoke cannabis while driving:",
          explanation: "It is illegal for both the driver AND passengers to drink alcohol or smoke cannabis in a moving vehicle.",
          handbookSection: "Alcohol and Drugs — Open Container Law",
          difficulty: 1,
          options: [
            { content: "Only for the driver", isCorrect: false },
            { content: "For both the driver and passengers", isCorrect: true },
            { content: "Only on freeways", isCorrect: false },
            { content: "Only for drivers under 21", isCorrect: false },
          ],
        },
        {
          content: "After a DUI arrest, you have how many days to request a hearing to contest your license suspension?",
          explanation: "You have 10 days from the date of arrest to request a DMV hearing. Miss this deadline and your license is suspended automatically.",
          handbookSection: "Alcohol and Drugs — DUI Consequences",
          difficulty: 3,
          options: [
            { content: "5 days", isCorrect: false },
            { content: "10 days", isCorrect: true },
            { content: "30 days", isCorrect: false },
            { content: "60 days", isCorrect: false },
          ],
        },
        {
          content: "If under 21 and found in possession of alcohol in a vehicle, your vehicle may be impounded for:",
          explanation: "California law allows the vehicle to be impounded for up to 30 days if a driver under 21 is found with alcohol.",
          handbookSection: "Alcohol and Drugs — Zero Tolerance",
          difficulty: 3,
          options: [
            { content: "24 hours", isCorrect: false },
            { content: "7 days", isCorrect: false },
            { content: "30 days", isCorrect: true },
            { content: "90 days", isCorrect: false },
          ],
        },
        {
          content: "Driving under the influence of marijuana is:",
          explanation: "Even though recreational marijuana is legal in California, driving under its influence is illegal. Cannabis impairs reaction time, coordination, and judgment.",
          handbookSection: "Alcohol and Drugs — Drug Impairment",
          difficulty: 1,
          options: [
            { content: "Legal since marijuana is legal in California", isCorrect: false },
            { content: "Illegal — it impairs driving ability", isCorrect: true },
            { content: "Only illegal for drivers under 21", isCorrect: false },
            { content: "Legal as long as BAC is under 0.08%", isCorrect: false },
          ],
        },
      ],
    },

    // ─── TOPIC 5: Lane Usage & Passing ─────────────────────────────────────────
    {
      name: "Lane Usage & Passing",
      nameEn: "Lane Usage & Passing",
      description: "Lane selection, passing rules, HOV lanes, center turn lanes",
      handbookUrl: "https://www.dmv.ca.gov/portal/handbook/california-driver-handbook/navigating-the-roads/",
      translations: [
        { language: "zh", name: "车道使用与超车", description: "车道选择、超车规则、HOV 车道、中央左转车道" },
        { language: "es", name: "Uso de Carriles y Adelantamiento", description: "Selección de carril, reglas para adelantar, carriles HOV y carriles de giro central" },
      ],
      questions: [
        {
          content: "How far in advance must you signal before turning or changing lanes?",
          explanation: "California law requires signaling at least 100 feet before turning or changing lanes. On freeways, signal approximately 5 seconds (about 400 feet) before exiting.",
          handbookSection: "Navigating the Roads — Turning",
          difficulty: 1,
          options: [
            { content: "25 feet", isCorrect: false },
            { content: "50 feet", isCorrect: false },
            { content: "100 feet", isCorrect: true },
            { content: "200 feet", isCorrect: false },
          ],
        },
        {
          content: "You may NOT pass another vehicle within how many feet of an intersection?",
          explanation: "Passing is prohibited within 100 feet of an intersection, railroad crossing, bridge, or tunnel.",
          handbookSection: "Navigating the Roads — Passing",
          difficulty: 2,
          options: [
            { content: "50 feet", isCorrect: false },
            { content: "100 feet", isCorrect: true },
            { content: "200 feet", isCorrect: false },
            { content: "300 feet", isCorrect: false },
          ],
        },
        {
          content: "How long may you drive in a center two-way left-turn lane before turning?",
          explanation: "You may only drive in a center two-way left-turn lane for a maximum of 200 feet while preparing to turn.",
          handbookSection: "Navigating the Roads — Center Turn Lane",
          difficulty: 2,
          options: [
            { content: "As long as needed", isCorrect: false },
            { content: "Up to 100 feet", isCorrect: false },
            { content: "Up to 200 feet", isCorrect: true },
            { content: "Up to 500 feet", isCorrect: false },
          ],
        },
        {
          content: "When entering a bike lane to prepare for a right turn, you may enter no more than how far before the intersection?",
          explanation: "You may merge into a bike lane no more than 200 feet before the intersection where you intend to turn right.",
          handbookSection: "Navigating the Roads — Bicycle Lanes",
          difficulty: 2,
          options: [
            { content: "50 feet", isCorrect: false },
            { content: "100 feet", isCorrect: false },
            { content: "200 feet", isCorrect: true },
            { content: "500 feet", isCorrect: false },
          ],
        },
        {
          content: "What is an HOV lane and who may use it?",
          explanation: "HOV (High Occupancy Vehicle) lanes are reserved for vehicles with 2+ occupants, motorcycles, buses, and some clean-air vehicles with special decals.",
          handbookSection: "Navigating the Roads — HOV Lanes",
          difficulty: 1,
          options: [
            { content: "A lane for heavy trucks and oversized vehicles", isCorrect: false },
            { content: "A lane for vehicles with 2+ occupants, motorcycles, and buses", isCorrect: true },
            { content: "A lane only for emergency vehicles", isCorrect: false },
            { content: "Open to all vehicles during off-peak hours", isCorrect: false },
          ],
        },
        {
          content: "The correct procedure for changing lanes is:",
          explanation: "Signal, check your mirror, check your blind spot by looking over your shoulder, then change lanes when safe. Never rely only on mirrors.",
          handbookSection: "Navigating the Roads — Changing Lanes",
          difficulty: 1,
          options: [
            { content: "Check mirrors and immediately move over", isCorrect: false },
            { content: "Signal, check mirrors, check blind spot, then change when safe", isCorrect: true },
            { content: "Look over your shoulder and change without signaling if clear", isCorrect: false },
            { content: "Honk to warn other drivers, then change lanes", isCorrect: false },
          ],
        },
        {
          content: "You may pass on the right ONLY when:",
          explanation: "Passing on the right is only allowed when the road has two or more lanes in your direction, the driver ahead is turning left, or on a one-way street.",
          handbookSection: "Navigating the Roads — Passing",
          difficulty: 2,
          options: [
            { content: "You are in a hurry and the left lane is blocked", isCorrect: false },
            { content: "The highway has 2+ lanes in your direction or the driver ahead is turning left", isCorrect: true },
            { content: "The speed limit is over 55 mph", isCorrect: false },
            { content: "The driver ahead is going 10 mph under the limit", isCorrect: false },
          ],
        },
        {
          content: "When merging onto a freeway from an on-ramp, you should:",
          explanation: "Use the on-ramp to accelerate to freeway speed before merging. Find a safe gap, signal, and merge smoothly. Never stop on an on-ramp unless forced to.",
          handbookSection: "Navigating the Roads — Freeway Merging",
          difficulty: 1,
          options: [
            { content: "Stop at the end of the ramp and wait for a gap", isCorrect: false },
            { content: "Accelerate to freeway speed and merge into a safe gap", isCorrect: true },
            { content: "Enter slowly and let freeway drivers adjust", isCorrect: false },
            { content: "Use the emergency lane until you reach freeway speed", isCorrect: false },
          ],
        },
        {
          content: "After passing a vehicle, you should return to your lane when:",
          explanation: "Return to your original lane only when you can see both headlights of the vehicle you passed in your rearview mirror. Cutting back too soon is dangerous.",
          handbookSection: "Navigating the Roads — Passing",
          difficulty: 2,
          options: [
            { content: "You are about 10 feet ahead of the passed vehicle", isCorrect: false },
            { content: "You can see both headlights of the passed vehicle in your rearview mirror", isCorrect: true },
            { content: "The passing lane is clear behind you", isCorrect: false },
            { content: "Immediately after passing the vehicle's front bumper", isCorrect: false },
          ],
        },
        {
          content: "On a freeway, before your exit, you should signal approximately how far in advance?",
          explanation: "On a freeway, signal approximately 5 seconds before your exit, which is roughly 400 feet at freeway speed.",
          handbookSection: "Navigating the Roads — Freeway Exits",
          difficulty: 2,
          options: [
            { content: "100 feet before the exit", isCorrect: false },
            { content: "200 feet before the exit", isCorrect: false },
            { content: "5 seconds (approximately 400 feet) before the exit", isCorrect: true },
            { content: "When you first see the exit sign", isCorrect: false },
          ],
        },
        {
          content: "Weaving between lanes in traffic is:",
          explanation: "Weaving in and out of lanes is dangerous, illegal, and rarely saves significant time. Each lane change puts you at risk for a collision.",
          handbookSection: "Navigating the Roads — Changing Lanes",
          difficulty: 1,
          options: [
            { content: "Acceptable when traffic is slow", isCorrect: false },
            { content: "Dangerous, illegal, and rarely saves time", isCorrect: true },
            { content: "Permitted on freeways with 3 or more lanes", isCorrect: false },
            { content: "Fine as long as you signal each lane change", isCorrect: false },
          ],
        },
        {
          content: "How far before a right turn should you position your vehicle in the right lane?",
          explanation: "Signal at least 100 feet before a right turn in a city or residential area, and move into the right lane before turning.",
          handbookSection: "Navigating the Roads — Turning",
          difficulty: 1,
          options: [
            { content: "50 feet", isCorrect: false },
            { content: "100 feet", isCorrect: true },
            { content: "200 feet", isCorrect: false },
            { content: "At the intersection", isCorrect: false },
          ],
        },
      ],
    },

    // ─── TOPIC 6: Safe Driving & Parking ───────────────────────────────────────
    {
      name: "Safe Driving & Parking",
      nameEn: "Safe Driving & Parking",
      description: "Following distance, distracted driving, night driving, parking rules",
      handbookUrl: "https://www.dmv.ca.gov/portal/handbook/california-driver-handbook/safe-driving/",
      translations: [
        { language: "zh", name: "安全驾驶与停车", description: "跟车距离、分心驾驶、夜间行驶、停车规则" },
        { language: "es", name: "Manejo Seguro y Estacionamiento", description: "Distancia de seguimiento, manejo distraído, manejo nocturno, reglas de estacionamiento" },
      ],
      questions: [
        {
          content: "The 3-second rule helps you:",
          explanation: "The 3-second rule maintains a safe following distance. Pick a fixed object ahead, and when the car in front passes it, count 3 seconds. If you reach the object before 3 seconds, you are too close.",
          handbookSection: "Safe Driving — Following Distance",
          difficulty: 1,
          options: [
            { content: "Determine when to change lanes", isCorrect: false },
            { content: "Maintain a safe following distance behind another vehicle", isCorrect: true },
            { content: "Calculate stopping distance from 55 mph", isCorrect: false },
            { content: "Judge whether you have time to make a yellow light", isCorrect: false },
          ],
        },
        {
          content: "What is the leading cause of distracted driving?",
          explanation: "Cell phones are the primary cause of distracted driving. California law prohibits holding a phone while driving — you must use a hands-free device.",
          handbookSection: "Safe Driving — Distracted Driving",
          difficulty: 1,
          options: [
            { content: "Eating while driving", isCorrect: false },
            { content: "Cell phones", isCorrect: true },
            { content: "Highway billboards", isCorrect: false },
            { content: "Loud music", isCorrect: false },
          ],
        },
        {
          content: "How far ahead should you scan the road while driving?",
          explanation: "Scan at least 10 to 15 seconds ahead (about a quarter mile on the highway). This gives time to identify and respond to hazards before they become emergencies.",
          handbookSection: "Safe Driving — Scanning the Road",
          difficulty: 2,
          options: [
            { content: "One car length ahead", isCorrect: false },
            { content: "3 to 4 seconds ahead", isCorrect: false },
            { content: "At least 10 to 15 seconds ahead", isCorrect: true },
            { content: "As far as headlights illuminate at night", isCorrect: false },
          ],
        },
        {
          content: "You should switch from high beams to low beams when an oncoming vehicle is within:",
          explanation: "Switch to low beams within 500 feet of an oncoming vehicle, and within 300 feet when following another vehicle.",
          handbookSection: "Safe Driving — Night Driving",
          difficulty: 2,
          options: [
            { content: "1,000 feet", isCorrect: false },
            { content: "500 feet", isCorrect: true },
            { content: "200 feet", isCorrect: false },
            { content: "100 feet", isCorrect: false },
          ],
        },
        {
          content: "California law requires headlights to be on:",
          explanation: "Headlights are required from 30 minutes after sunset to 30 minutes before sunrise, and whenever visibility is less than 1,000 feet.",
          handbookSection: "Safe Driving — Night Driving",
          difficulty: 2,
          options: [
            { content: "Only after it gets completely dark", isCorrect: false },
            { content: "30 minutes after sunset until 30 minutes before sunrise", isCorrect: true },
            { content: "Only during rain or fog", isCorrect: false },
            { content: "Only on unlit roads", isCorrect: false },
          ],
        },
        {
          content: "In fog, you should use:",
          explanation: "Use low-beam headlights in fog — not high beams. High beams reflect off fog particles and reduce your visibility.",
          handbookSection: "Safe Driving — Driving in Bad Weather",
          difficulty: 1,
          options: [
            { content: "High-beam headlights for maximum visibility", isCorrect: false },
            { content: "Low-beam headlights or fog lights", isCorrect: true },
            { content: "Hazard lights and high beams together", isCorrect: false },
            { content: "No headlights — they reflect off fog", isCorrect: false },
          ],
        },
        {
          content: "You must not park within how many feet of a fire hydrant?",
          explanation: "California prohibits parking within 15 feet of a fire hydrant to ensure fire trucks can access it quickly.",
          handbookSection: "Safe Driving — Parking Rules",
          difficulty: 2,
          options: [
            { content: "5 feet", isCorrect: false },
            { content: "10 feet", isCorrect: false },
            { content: "15 feet", isCorrect: true },
            { content: "20 feet", isCorrect: false },
          ],
        },
        {
          content: "When parking UPHILL with a curb, your front wheels should be turned:",
          explanation: "Parking uphill with a curb: turn wheels AWAY from the curb (left). If brakes fail, the car rolls back and the curb stops it.",
          handbookSection: "Safe Driving — Parking on Hills",
          difficulty: 2,
          options: [
            { content: "Toward the curb (right)", isCorrect: false },
            { content: "Away from the curb (left)", isCorrect: true },
            { content: "Straight ahead", isCorrect: false },
            { content: "It does not matter — just set the parking brake", isCorrect: false },
          ],
        },
        {
          content: "When parking DOWNHILL with a curb, your front wheels should be turned:",
          explanation: "Parking downhill with a curb: turn wheels TOWARD the curb (right). If brakes fail, the car rolls forward and the curb stops it.",
          handbookSection: "Safe Driving — Parking on Hills",
          difficulty: 2,
          options: [
            { content: "Away from the curb (left)", isCorrect: false },
            { content: "Toward the curb (right)", isCorrect: true },
            { content: "Straight ahead", isCorrect: false },
            { content: "It does not matter — engage the emergency brake", isCorrect: false },
          ],
        },
        {
          content: "You must not park within how many feet of a stop sign?",
          explanation: "Parking within 30 feet of a stop sign blocks visibility for drivers checking cross-traffic.",
          handbookSection: "Safe Driving — Parking Rules",
          difficulty: 3,
          options: [
            { content: "15 feet", isCorrect: false },
            { content: "20 feet", isCorrect: false },
            { content: "30 feet", isCorrect: true },
            { content: "50 feet", isCorrect: false },
          ],
        },
        {
          content: "Driver fatigue is dangerous because it:",
          explanation: "Driver fatigue reduces alertness, slows reaction times, and can cause microsleep — brief moments of falling asleep without realizing it. Fatigue impairs driving similarly to alcohol.",
          handbookSection: "Safe Driving — Fatigue",
          difficulty: 1,
          options: [
            { content: "Makes you drive faster than normal", isCorrect: false },
            { content: "Increases reaction time and can cause you to fall asleep at the wheel", isCorrect: true },
            { content: "Actually improves focus by reducing distraction", isCorrect: false },
            { content: "Only affects you on trips over 4 hours", isCorrect: false },
          ],
        },
        {
          content: "If your accelerator gets stuck while driving, you should:",
          explanation: "Shift to Neutral to disconnect the engine, steer to the side of the road, and apply brakes. Do NOT turn off the ignition while moving — it disables power steering and brakes.",
          handbookSection: "Safe Driving — Vehicle Emergencies",
          difficulty: 3,
          options: [
            { content: "Turn off the ignition immediately", isCorrect: false },
            { content: "Shift to Neutral, steer to the side, and apply the brakes", isCorrect: true },
            { content: "Pump the brakes rapidly while steering straight", isCorrect: false },
            { content: "Pull the parking brake immediately to stop", isCorrect: false },
          ],
        },
        {
          content: "What should you do if you experience a tire blowout while driving?",
          explanation: "In a blowout: do NOT brake suddenly. Hold the wheel firmly, ease off the accelerator, steer straight, let the car slow naturally, then gently steer to the shoulder.",
          handbookSection: "Safe Driving — Vehicle Emergencies",
          difficulty: 2,
          options: [
            { content: "Immediately apply the brakes hard to stop quickly", isCorrect: false },
            { content: "Hold the wheel firmly, ease off the gas, steer straight, and slow gradually", isCorrect: true },
            { content: "Quickly turn the wheel toward the blown tire", isCorrect: false },
            { content: "Turn on hazard lights and stop wherever you are", isCorrect: false },
          ],
        },
        {
          content: "How far must you park from a railroad crossing?",
          explanation: "You must not park within 7.5 feet of a railroad track. This keeps the track clear for trains and emergency vehicles.",
          handbookSection: "Safe Driving — Parking Rules",
          difficulty: 3,
          options: [
            { content: "5 feet", isCorrect: false },
            { content: "7.5 feet", isCorrect: true },
            { content: "15 feet", isCorrect: false },
            { content: "25 feet", isCorrect: false },
          ],
        },
        {
          content: "When stopped by police, you should acknowledge by:",
          explanation: "When a police officer signals you to stop, turn on your RIGHT turn signal to show you have seen them, then pull to the right side of the road safely and stop.",
          handbookSection: "Safe Driving — Traffic Stops",
          difficulty: 2,
          options: [
            { content: "Turning on your left turn signal", isCorrect: false },
            { content: "Turning on your right turn signal and pulling safely to the right", isCorrect: true },
            { content: "Flashing your headlights a few times", isCorrect: false },
            { content: "Stopping immediately wherever you are", isCorrect: false },
          ],
        },
      ],
    },
  ],
};
